### ISSUE TITLE
Storage for 8 wagon trains

### ISSUE THREAD

**Issue by bagalas** [nicolas-lang/Factorio.LongStorageTanks#5]
HI,

Awesome mod. The tanks are made for 2-4-6 wagon trains but I use 8 wagons. Any chance to add one more tier to the tanks?

**Comment by nicolas-lang** [comment]
Check the mod settings, you can set the desired sizes yourself.
There is no migration though, if you remove a size, it just disappears with all it's contents.

closed as already implemented
